sudo: required
services:
    - docker 
    
before_install:
    - docker build -t azsymtisi/docker-react -f Dockerfile.dev .
    


script:
    - docker run azsymtisi/docker-react npm run test -- --coverage